# Generated by Django 2.0.5 on 2018-05-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='groupss',
        ),
    ]
